# Script för att skapa NewtonBank databas

DROP SCHEMA IF EXISTS NewtonBank;
CREATE SCHEMA NewtonBank CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALL ON NewtonBank.* TO root@localhost IDENTIFIED BY 'root';

USE NewtonBank;

CREATE TABLE Customer ( 
	personNr BIGINT UNSIGNED NOT NULL,
	name VARCHAR(30) NOT NULL,
	PRIMARY KEY(personNr)
) ENGINE=INNODB;

CREATE TABLE Account (
		accountId INT UNSIGNED NOT NULL AUTO_INCREMENT,
		personNr BIGINT UNSIGNED NOT NULL,
		accountType ENUM('SPARKONTO', 'KREDITKONTO') NOT NULL,
		rate DECIMAL(4, 2) UNSIGNED NOT NULL DEFAULT 0,
		balance DECIMAL(12, 2) NOT NULL DEFAULT 0,
		credit INT UNSIGNED,
		creditRate DECIMAL(4, 2) UNSIGNED,
		PRIMARY KEY(accountId),
	 	FOREIGN KEY (personNr) REFERENCES Customer(personNr) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB AUTO_INCREMENT=1001;

CREATE TABLE Transaction (
		transId INT UNSIGNED NOT NULL AUTO_INCREMENT,
		accountId INT UNSIGNED NOT NULL,
		transDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		transType ENUM('IN', 'UT') NOT NULL,
		amount DECIMAL(12, 2) NOT NULL,
		balance DECIMAL(12, 2) NOT NULL,
		PRIMARY KEY(transId),
	 	FOREIGN KEY (accountId) REFERENCES Account(accountId) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=INNODB;

